spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/<your database>
    username:
    password:

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
      issuer: ${API Voll.med:API Voll.med}

BITLY_TOKEN: Seu token vai aqui